title: Miss Star International
description: Miss Star International Website
theme: jekyll-theme-minimal
baseurl: /missstarweb2024
url: https://maxxxcaram.github.io
include: [".nojekyll"]
exclude: ["SHARING.md", "deployment-guide.md", "github-pages-guide.md", "compartir-sitio.bat", "compartir-sitio.ps1"] 